### ISSUE TITLE
Support for a major version tag

### ISSUE THREAD

**Issue by houstonj1** [devth/helm-docker#127]
Hey @devth, thanks for building and maintaining such an awesome Helm image. I was wondering if you'd be open to publishing a major version tag as well as the current major.minor.patch version tags

For example:
`devth/helm:v3` as well as `devth/helm:v3.6.3`

If you are open to the idea, I'd be happy to collaborate!

**Comment by devth** [comment]
Fixed by https://github.com/devth/helm-docker/pull/130
