### ISSUE TITLE
Upgrade to Helm 3.7.0 (and improve the GH Actions!)

### ISSUE THREAD

**Issue by devth** [devth/helm-docker#132]
v3.7.0 released 2021-09-15T19:38:13Z
https://github.com/helm/helm/releases/tag/v3.7.0

**Comment by devth** [comment]
@houstonj1 it didn't find a new version for `3.7.0`: https://github.com/devth/helm-docker/runs/3614314613?check_suite_focus=true

Because `if grep -q "ENV VERSION v3.7.0" Dockerfile` isn't precise enough!

**Comment by devth** [comment]
I think we need: `grep -q "ENV VERSION v3.7.0$" Dockerfile`. I'll try it out!

**Comment by houstonj1** [comment]
First try! 😅  Also excited to see how the major version update works out. Does a tag update kick of a build on Docker hub?

**Comment by devth** [comment]
It previously did. With [Docker Hub changes builds are no longer available for free/oss projects](https://www.docker.com/blog/changes-to-docker-hub-autobuilds/).

I kinda forgot about it till now. Looks like we need to add an action to build/push the docker image, so your contributions setting up GH Actions were timely!

**Comment by devth** [comment]
The other thing I'm thinking about is if the GH Action could close the GH Issue that triggered it.

**Comment by houstonj1** [comment]
I think as long as the commit message contains "closes #<issue-number>", it should work. Now how to get the issue number...

**Comment by devth** [comment]
Yep. I partially figured it out. The event payload is available as a JSON file. You can parse and extract with jq.

**Comment by houstonj1** [comment]
I can't seem to find great docs on how to parse the issue object from GHA, but that seems promising

**Comment by devth** [comment]
Yeah it was hard to find. Check out https://www.freecodecamp.org/news/publishing-github-event-data-with-github-actions-and-pages/ for an example.

**Comment by devth** [comment]
Added [this](https://github.com/devth/helm-docker/blob/master/.github/workflows/docker.yaml) to publish Docker images. `v3.7.1` is now being built at https://github.com/devth/helm-docker/actions/runs/1339818481

It works for tags that were manually pushed, but I'm not sure if it'll work for tags pushed by other GitHub Actions. [This thread](https://github.community/t/new-tag-does-not-trigger-an-event/121511) makes me think it won't, but we won't know until the next helm release happens (unless we hack together some test).
