### ISSUE TITLE
Upgrade helmfile/vals (currently v0.14.0) to fix high CVE's 

### ISSUE THREAD

**Issue by MartijnPDirekt** [devth/helm-docker#189]
The Docker image contains several CVE's, which are almost all from [https://github.com/helmfile/vals](url). This repo already released version v0.25.0, that resolves a lot of CVE's. Could you please upgrade??
![v3 12 1](https://github.com/devth/helm-docker/assets/124152066/d44d0b7b-81cc-4efc-b666-ee1c7c07f320)

Thanks in advance.

**Comment by MartijnPDirekt** [comment]
v0.14.0
![image](https://github.com/devth/helm-docker/assets/124152066/460e2119-d535-44be-ba08-bc589ef87a5a)

v0.25.0
![image](https://github.com/devth/helm-docker/assets/124152066/570f85f8-86ef-49b0-85e9-2ccedd36ec3c)

**Comment by devth** [comment]
Hi @MartijnPDirekt, I bumped the version. Will be included in the next release.
