### ISSUE TITLE
Helm2to3 is no longer actively maintained

### ISSUE THREAD

**Issue by MartijnPDirekt** [devth/helm-docker#193]
Hi Trevor,

https://github.com/helm/helm-2to3/ contains several high CVE's, that are all fixed by dependabot, but are not approved by the maintainer (https://github.com/helm/helm-2to3/issues/228)

How would you like to proceed, given helm 2 is deprecated almost 3 years. 
A possbile solution would be to leave this repo untouched and start a new one that supports Helm v3 only. That will make the image even lighter. 

I am curious to hear your thoughts.

Kr,
Martijn

**Comment by devth** [comment]
Thanks for raising this issue @MartijnPDirekt! I'm fine just removing it from this image given how long Helm 3 has been out.

**Comment by MartijnPDirekt** [comment]
Hi Trevor,
You're awesome. Thanks for the fast response and resolution!
