### ISSUE TITLE
Version tag

### ISSUE THREAD

**Issue by htch** [devth/helm-docker#2]
First off, thanks for this image, I use it for all of my CI builds.

Maybe we can have version tags for different image versions e.g. devth/helm:2.6.2, devth/helm:2.7.0, so that upgrades to a new version would happen more predictably?

**Comment by devth** [comment]
Hi @htch, glad it's useful for you.

I am currently using tags. See the list on [Docker hub](https://hub.docker.com/r/devth/helm/tags/). So it's up to you if you want to use `latest` (which is always the most recent release) or a tagged version.

**Comment by htch** [comment]
Ok thanks for pointing out.
