### ISSUE TITLE
Upgrade helm-diff plugin to v2.10.0+1

### ISSUE THREAD

**Issue by MPV** [devth/helm-docker#30]
Hi @devth,
Would you be open to upgrading the `helm-diff` plugin to the `v2.10.0+1` version?

It includes a fix for diffing against specific namespaces:
https://github.com/databus23/helm-diff/pull/85/commits/c6949166ef7242393b47acd3479177616ba63118

**Comment by devth** [comment]
@MPV Yep!

**Comment by MPV** [comment]
I'm currently using your `devth/helm:v2.10.0` image tag.

Maybe you'd be okay updating both that and `v2.11.0`? 😊 

Otherwise I probably should be looking to upgrade my Tillers to 2.11 soon either way... 😅

**Comment by MPV** [comment]
Thanks @devth — worked like a charm! 👏
