### ISSUE TITLE
Upgrade to Helm Client Security Fix (Moderate)

### ISSUE THREAD

**Issue by devth** [devth/helm-docker#37]
v2.12.2 released 2019-01-14T19:02:37Z
https://github.com/helm/helm/releases/tag/v2.12.2

**Comment by codecex** [comment]
Hello, 

Just an appointment.

Helm docker version that you have uploaded to dockerhub tagged as latest and v2.12.2 is not really v2.12.2, both of them are: v2.12.0. 
Try to do in your local machine docker pull devth/helm:latest or devth/helm:v2.12.2 and then login into the container and you will see that helm version shows "v2.12.0".

Anyway i built your dockerfile with the correct latest version and works like a charm.

Thanks for your work.

**Comment by devth** [comment]
@codecex strange! I'll try rebuilding. Thanks for letting me know!

**Comment by devth** [comment]
@codecex forgot to bump version in previous builds. Tried to look into a way to get it from ENV for automated builds on dockerhub but don't see support for it. Latest build v2.12.3 (currently building) should be correct.
