### ISSUE TITLE
Upgrade to Helm v2.13.0 - Raspberry Caramel Latte Edition

### ISSUE THREAD

**Issue by devth** [devth/helm-docker#42]
v2.13.0 released 2019-02-27T18:46:02Z
https://github.com/helm/helm/releases/tag/v2.13.0

**Comment by markmssd** [comment]
Hey, a docker image did not get created for v2.13.0 (https://hub.docker.com/r/devth/helm/tags), and it says in the README.md that `Docker images are automatically built on Docker Hub`... am I missing something?

**Comment by devth** [comment]
Looks like Docker Hub [changed things up recently](https://success.docker.com/article/i-have-issues-triggering-autobuilds) 😞

Fresh builds are running right now.

**Comment by markmssd** [comment]
I see it now, thanks @devth !! Amazing docker image btw

**Comment by devth** [comment]
Awesome. Thanks!
